# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zverok's space
email: zverok.offline@gmail.com
description: I don't build systems. I imagine them, then write them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zverok.space" # the base hostname & protocol for your site
permalink: "/blog/:year-:month-:day-:title.html"
twitter_username: zverok
github_username:  zverok
paginate: 50
theme-dark: false #Set to true to change to dark website theme

# plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
